version: "2"
run:
  tests: true
linters:
  default: none
  enable:
    - errcheck
    - goconst
    - gocritic
    - gocyclo
    - govet
    - ineffassign
    - nakedret
    - prealloc
    - staticcheck
    - unconvert
    - unparam
    - unused
  settings:
    dupl:
      threshold: 200
    errcheck:
      check-blank: true
    govet:
      enable:
        - shadow
    funlen:
      lines: 80
      statements: 50
    gocognit:
      min-complexity: 30
    gocyclo:
      min-complexity: 20
    nakedret:
      max-func-lines: 50
    staticcheck:
      checks:
        - "all"
        - "-SA6000"
        - "-QF1001"
        - "-SA2002"
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      - path: (.+)\.go$
        text: should have comment
      - path: (.+)\.go$
        text: always receives
      - path: (.+)\.go$
        text: parameter .* is always
      - path: (.+)\.go$
        text: comment on exported .* should be of the form
    paths:
      - "bin$"
      - "\\.git$"
      - "misc$"
      - "spec$"
      - "pkg$"
      - "common$"
      - "_easyjson.go"
      - "jwt_example.go"
      - "pb.go"
issues:
  max-issues-per-linter: 0
  max-same-issues: 0
formatters:
  exclusions:
    generated: lax
